### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by vincentk** [ezhulenev/scala-openbook#1]
Your repository is missing a license file. Is it open source? And if so, could you specify the license?

**Comment by ezhulenev** [comment]
Added MIT license to repo.

**Comment by vincentk** [comment]
Many thanks! Could you please consider doing the same also for your marketDB project, as I'm curious if it might be of use for a current project of mine.

**Comment by ezhulenev** [comment]
yes sure, will add it too

**Comment by vincentk** [comment]
Hi, the license statement says that the copyright holder of this code is Paul Chiusano. Are you sure?

**Comment by ezhulenev** [comment]
ouch, copy-pasta from scalaz ;)
