### ISSUE TITLE
Unclarity w.r.t. version numbering.

### ISSUE THREAD

**Issue by vincentk** [ezhulenev/scala-openbook#2]
Both in the [README.md](https://github.com/ezhulenev/scala-openbook/blob/master/README.md) and in the [build.sbt](https://github.com/ezhulenev/scala-openbook/blob/master/build.sbt) the current version of this library would seem to be 0.0.6. However, the bintray repository advertised in the README only contains an [0.0.1](http://dl.bintray.com/ezhulenev/releases/com/scalafi/openbook/scala-openbook_2.11/0.0.1/) release. My understanding is that to bring these two back in sync, it would be good if you could release the current version to bintray?

The parser looks cute by the way. I'd be more than happy to use it.

**Comment by vincentk** [comment]
In the meantime, I can work around the presumed issue by preparing for myself a local install (I'm using `mvn`):

```
> sbt publish-m2
```

**Comment by vincentk** [comment]
Hi, I've taken the liberty of publishing an 0.0.6 version to my bintray repository at
https://dl.bintray.com/vincentk/releases .

**Comment by ezhulenev** [comment]
I've just published 0.0.7 after merge
