### ISSUE TITLE
Delta vs. Full state updates

### ISSUE THREAD

**Issue by vincentk** [ezhulenev/scala-openbook#7]
Currently looking at the logic in `OrderBook.update`. It would seem to me that you assume that the order message describes a full state. E.g. also consider the `OrderBookSpec`. Volumes get replaced, not added. I do not think this is the correct way to handle things. I.e. in `OrderBookSpec`, I would expect that this line:

```
assert(orderBooks.next().buy.get(order2.priceNumerator).get == order2.volume)
```

would need to be replaced by

```
assert(orderBooks.next().buy.get(order2.priceNumerator).get == order2.volume + order1.volume)
```

given that the test order messages are flagged with `MsgType.DeltaUpdate`.

**Comment by vincentk** [comment]
Not sure about the terminology. The `TAQ NYSE OPENBOOK ULTRA CLIENT SPECIFICATION v. 1.1` only describes the syntax, not the semantics of these messages.

**Comment by ezhulenev** [comment]
In Table2 (p. 8): Volume - This field contains the total interest quantity at a price point.

I'm not 100% sure, but looks like it's aggregated volume for price level

**Comment by vincentk** [comment]
Ah, indeed. Presumably, one would need to have to look at `ChgQty`, if one wanted to look at the volume difference for delta messages. Many thanks for the clarification.
